CREATE TABLE IF NOT EXISTS stats
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(250)                NOT NULL,
    uri       VARCHAR(250)                NOT NULL,
    ip        VARCHAR(250)                NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);